apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: clv
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: openai
spec:
  source:
    git:
      url: https://github.com/cpage-pivotal/dallecool
      ref:
        branch: testing
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  serviceClaims:
    - name: openai
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: openai-claim
    - name: redis
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: redis-claim

